from pathlib import Path
import re,xml.etree.ElementTree as ET
root=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site"); out=root/"pa"; out.mkdir(exist_ok=True); base="https://agurkin2021-gif.github.io/vps-for-n8n/"
P=[
("index.html","n8n ਲਈ VPS: Self-Hosted Server Guide","n8n ਲਈ VPS ਚੁਣਦੇ ਸਮੇਂ CPU, RAM, NVMe, Docker, PostgreSQL, HTTPS, latency ਅਤੇ production workload ਨੂੰ ਇਕੱਠੇ ਵੇਖੋ।","n8n ਲਈ VPS: Production ਲਈ ਸਹੀ Server","ਹਲਕੇ automation ਲਈ 1–2 vCPU / 2 GB RAM ਚੱਲ ਸਕਦੀ ਹੈ। ਛੋਟੇ production ਲਈ 2 vCPU / 4 GB ਇੱਕ practical starting point ਹੈ; AI ਅਤੇ heavy workflows ਲਈ 4+ vCPU / 8 GB+ ਵੇਖੋ।","India commercial factors","₹/month ਅਤੇ renewal ਨਾਲ India region latency, NVMe, root access, backups, uptime/SLA ਅਤੇ vertical scaling ਵੇਖੋ।"),
("best-vps-for-n8n.html","n8n ਲਈ Best VPS India: RAM, CPU ਅਤੇ Price","n8n ਲਈ best VPS ਨੂੰ RAM, CPU, NVMe, India latency, SLA, bandwidth ਅਤੇ ₹ pricing ਨਾਲ compare ਕਰੋ।","n8n ਲਈ Best VPS ਕਿਵੇਂ ਚੁਣੀਏ","2 GB testing/light workload ਲਈ ਹੋ ਸਕਦੀ ਹੈ; Docker + PostgreSQL ਵਾਲੇ production ਲਈ 4 GB headroom practical ਹੈ।","Comparison criteria","Intro price ਤੋਂ ਇਲਾਵਾ renewal, bandwidth, snapshots, SLA, support scope ਅਤੇ upgrade cost compare ਕਰੋ।"),
("n8n-hosting-india.html","n8n Hosting India: Managed vs Self-Hosted VPS","India ਵਿੱਚ n8n hosting ਲਈ managed hosting, one-click deployment ਅਤੇ self-managed VPS ਨੂੰ price, support, backup ਅਤੇ control ਨਾਲ compare ਕਰੋ।","n8n Hosting India: Managed ਜਾਂ Self-Managed","Managed hosting setup, SSL, updates, monitoring ਅਤੇ backups ਸੰਭਾਲ ਸਕਦੀ ਹੈ; self-managed VPS ਵੱਧ control ਦਿੰਦਾ ਹੈ ਪਰ operations ਤੁਹਾਡੀ responsibility ਹੈ।","Commercial gap","₹ pricing, execution limits, root access, backups, India data location, migration, support ਅਤੇ scaling scope compare ਕਰੋ।"),
("n8n-vps-requirements.html","n8n VPS Requirements: RAM, CPU ਅਤੇ Storage","n8n VPS requirements executions, concurrency, payload, PostgreSQL, retention ਅਤੇ binary data ਤੇ depend ਕਰਦੇ ਹਨ।","n8n VPS Requirements","Testing: 1–2 vCPU / 2 GB; small production: 2 vCPU / 4 GB; heavy workflows: 4+ vCPU / 8 GB+.","Upgrade signals","OOM/restarts, swapping, sustained CPU/RAM, execution latency ਅਤੇ backlog resource pressure ਦੇ signals ਹਨ।"),
("n8n-cloud-vs-self-hosted.html","n8n Cloud vs Self-Hosted: Cost ਅਤੇ Control","n8n Cloud ਅਤੇ self-hosted VPS ਨੂੰ executions, ₹ cost, maintenance, data control, backups ਅਤੇ security ਨਾਲ compare ਕਰੋ।","n8n Cloud vs Self-Hosted VPS","Cloud infrastructure management ਘਟਾਉਂਦਾ ਹੈ; self-hosted deployment/data control ਵਧਾਉਂਦਾ ਹੈ ਪਰ OS, network, updates, monitoring ਅਤੇ recovery ਤੁਹਾਡੀ responsibility ਹੈ।","TCO","VPS rent ਦੇ ਨਾਲ domain, backup, monitoring, admin time ਅਤੇ execution growth ਜੋੜੋ; ਸਿਰਫ monthly server price compare ਨਾ ਕਰੋ।"),
("n8n-queue-mode.html","n8n Queue Mode: Redis, Workers ਅਤੇ Scaling","n8n queue mode ਨੂੰ Redis, PostgreSQL, workers, concurrency ਅਤੇ encryption key ਨਾਲ production scale ਕਰੋ।","n8n Queue Mode ਅਤੇ Workers","Main trigger/webhook ਲੈਂਦਾ ਹੈ, Redis queue ਰੱਖਦਾ ਹੈ ਅਤੇ workers executions ਚਲਾਉਂਦੇ ਹਨ; shared PostgreSQL ਵਰਤੋ।","Production gap","Main ਅਤੇ workers ਇੱਕੋ N8N_ENCRYPTION_KEY share ਕਰਨ; worker concurrency ਅਤੇ DB connection pool ਇਕੱਠੇ size ਕਰੋ।"),
("n8n-vps-security.html","n8n VPS Security: Production Hardening","Self-hosted n8n ਲਈ HTTPS, firewall, SSH, MFA, updates, API restrictions ਅਤੇ execution-data protection ਲਾਜ਼ਮੀ ਹਨ।","n8n VPS Security Checklist","Reverse proxy/TLS, firewall, SSH keys, MFA ਅਤੇ regular updates ਵਰਤੋ; 5678/5432 ਨੂੰ ਬਿਨਾਂ ਲੋੜ public ਨਾ ਕਰੋ।","Data protection","Credentials ਅਤੇ execution data protect ਕਰੋ, unnecessary nodes/API access restrict ਕਰੋ ਅਤੇ retention/pruning configure ਕਰੋ।"),
("n8n-backup-restore.html","n8n Backup ਅਤੇ Restore: Database ਤੇ Encryption Key","n8n backup ਵਿੱਚ PostgreSQL/database, persistent data ਅਤੇ N8N_ENCRYPTION_KEY ਨੂੰ off-server ਸੁਰੱਖਿਅਤ ਰੱਖੋ।","n8n Backup ਅਤੇ Restore","Workflow export alone ਕਾਫ਼ੀ ਨਹੀਂ। DB, volumes/config ਅਤੇ encryption key backup ਕਰੋ।","Recovery gap","Regular test restore ਕਰੋ; same encryption key ਤੋਂ ਬਿਨਾਂ encrypted credentials readable ਨਹੀਂ ਹੋਣਗੇ।"),
("install-n8n-vps-docker.html","VPS ਤੇ n8n Install: Docker, PostgreSQL ਅਤੇ HTTPS","VPS ਤੇ Docker/Compose, PostgreSQL, domain, HTTPS ਅਤੇ reverse proxy ਨਾਲ n8n production deploy ਕਰੋ।","VPS ਤੇ n8n Docker ਨਾਲ Install ਕਰੋ","Ubuntu/Debian → Docker → PostgreSQL → persistent storage → domain/DNS → HTTPS/reverse proxy → webhook test → backup.","Production settings","N8N_ENCRYPTION_KEY, WEBHOOK_URL ਅਤੇ timezone set ਕਰੋ; image version pin ਕਰੋ ਅਤੇ database/n8n ports direct Internet ਤੇ expose ਨਾ ਕਰੋ।")]
links=" · ".join(f'<a href="{x[0]}">{x[2].split(":")[0]}</a>' for x in P)
for fn,title,desc,h1,p1,h2,p2 in P:
 url=base+"pa/"+("" if fn=="index.html" else fn)
 s=f'''<!doctype html><html lang="pa"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{title}</title><meta name="description" content="{desc}"><meta name="robots" content="index,follow"><link rel="canonical" href="{url}"><link rel="alternate" hreflang="pa" href="{url}"><link rel="alternate" hreflang="en" href="{base}"><link rel="alternate" hreflang="x-default" href="{base}"><link rel="icon" href="../favicon.svg"><link rel="stylesheet" href="../styles.css"></head><body><header><a class="brand" href="index.html">n8n<span>VPS</span></a><div class="lang-switch"><button type="button">ਪੰਜਾਬੀ &#9662;</button><div class="lang-menu"><a href="../">English</a><a href="../hi/">हिन्दी</a><a href="../bn/">বাংলা</a><a href="../ja/">日本語</a><a href="./">ਪੰਜਾਬੀ</a></div></div></header><main><section class="section"><h1>{h1}</h1><p class="lead">{desc}</p><div class="actions"><a class="primary" href="https://www.vdsina.com/?partner=ni8gzrvz75" rel="sponsored nofollow">VPS options ਵੇਖੋ</a></div></section><section class="section dark"><h2>{h2}</h2><p>{p1}</p></section><section class="section"><h2>Production intent</h2><p class="intro">{p2}</p></section><section class="section dark"><p>{links}</p></section></main></body></html>'''
 (out/fn).write_text(s,encoding="utf-8")
urls=[]
for f in root.rglob("*.html"):
 if ".git" in f.parts or f.name=="404.html": continue
 rel=f.relative_to(root).as_posix()
 if rel.endswith("/index.html"): rel=rel[:-10]
 elif rel=="index.html": rel=""
 urls.append(base+rel)
(root/"sitemap.xml").write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+"\n".join(f'  <url><loc>{u}</loc></url>' for u in sorted(set(urls)))+'\n</urlset>\n',encoding="utf-8")
print("PA",len(list(out.glob("*.html"))),"URLS",len(set(urls)))
