from pathlib import Path
import re
r=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site"); f=r/"ru"/"index.html"; s=f.read_text(encoding="utf-8")
# preserve head/header/hero and replace main remainder with full RU content
hero=re.search(r'(<main><section class="hero">.*?</section>)',s,re.S).group(1)
tail=s[s.find("</main>"):]
content=r'''
<section id="workloads" class="section"><p class="eyebrow">ПОДБОР ПО НАГРУЗКЕ</p><h2>Какой VPS нужен n8n под вашу нагрузку</h2><p class="intro">Количество workflows само по себе почти ничего не говорит. Важнее параллельные executions, размер payload, AI-ноды, Code nodes, binary data и сервисы рядом с n8n.</p><div class="cards"><article><span>01</span><h3>Лёгкая нагрузка</h3><b>1–2 vCPU · 2 GB RAM</b><p>Обучение, тесты, API-запросы и расписания с небольшой параллельностью.</p></article><article class="featured"><span>02 · БАЗОВЫЙ PRODUCTION</span><h3>Небольшой production</h3><b>2 vCPU · 4 GB RAM</b><p>Docker Compose, PostgreSQL, HTTPS, backups и запас по памяти.</p></article><article><span>03</span><h3>Тяжёлые и AI workflow</h3><b>4+ vCPU · 8 GB+ RAM</b><p>AI, большие JSON, файлы, Code nodes и несколько одновременных executions.</p></article><article><span>04</span><h3>Queue mode</h3><b>4+ vCPU · 8–16+ GB</b><p>PostgreSQL, Redis и workers для высокой параллельности.</p></article></div></section>
<section id="save" class="section dark"><p class="eyebrow">ОПТИМИЗАЦИЯ ДО АПГРЕЙДА</p><h2>Сначала уберите лишнюю нагрузку, потом увеличивайте VPS</h2><div class="cards"><article><h3>Execution data</h3><p>Настройте pruning и не храните успешные executions дольше необходимого.</p></article><article><h3>Concurrency</h3><p>Разносите тяжёлые расписания и не запускайте memory-heavy задачи одновременно без необходимости.</p></article><article><h3>Большие данные</h3><p>Сокращайте payload, binary data и ненужную передачу больших объектов между nodes.</p></article><article><h3>Измеряйте</h3><p>Следите за RAM, CPU, disk и execution duration. Масштабируйте по измеренной нагрузке.</p></article></div></section>
<section id="requirements" class="split"><div><p class="eyebrow">РЕАЛЬНЫЕ ТРЕБОВАНИЯ</p><h2>Требования n8n к VPS</h2><p>Минимальная конфигурация не равна production-конфигурации. Docker, PostgreSQL и reverse proxy требуют запаса.</p></div><div class="requirements"><div><b>CPU</b><span>1–2 vCPU для лёгких задач; больше ядер при transformations и concurrency.</span></div><div><b>RAM</b><span>2 GB тесты · 4 GB небольшой production · 8 GB+ тяжёлые нагрузки.</span></div><div><b>Storage</b><span>NVMe для PostgreSQL, execution history, logs и Docker data; ориентир 40–80 GB с поправкой на retention.</span></div></div></section>
<section id="architecture" class="section dark"><p class="eyebrow">PRODUCTION ARCHITECTURE</p><h2>Надёжная схема, а не просто запущенный контейнер</h2><div class="pipeline"><span>HTTPS</span><i>→</i><span>Reverse Proxy</span><i>→</i><span>n8n</span><i>→</i><span>PostgreSQL</span><i>→</i><span>Backup</span></div><p>Для queue mode добавляются Redis и workers. Все instances должны использовать общий N8N_ENCRYPTION_KEY.</p></section>
<section id="production" class="section"><p class="eyebrow">PRODUCTION CHECKLIST</p><h2>Что нужно кроме CPU и RAM</h2><div class="cards"><article><h3>Docker + PostgreSQL</h3><p>Persistent volumes и закрытая от интернета база данных.</p></article><article><h3>HTTPS + Webhooks</h3><p>Reverse proxy, домен и корректный WEBHOOK_URL.</p></article><article><h3>Encryption + Backup</h3><p>Сохраняйте N8N_ENCRYPTION_KEY вместе с DB и persistent data.</p></article><article><h3>Retention</h3><p>Контролируйте execution history и binary data, чтобы диск не рос бесконтрольно.</p></article></div></section>
<section id="operations" class="split"><div><p class="eyebrow">ЭКСПЛУАТАЦИЯ</p><h2>Self-hosted означает ответственность владельца</h2><p>ОС, сеть, производительность, Docker, обновления, monitoring и восстановление находятся на стороне владельца VPS.</p></div><div class="requirements"><div><b>Domain & DNS</b><span>Стабильный HTTPS-адрес для editor и webhooks.</span></div><div><b>Updates</b><span>Фиксируйте версии контейнера и делайте backup перед обновлением.</span></div><div><b>Monitoring</b><span>OOM/restarts, swap, высокая CPU/RAM и рост latency — сигналы нехватки ресурсов.</span></div><div><b>Security</b><span>Firewall, SSH keys, MFA; не публикуйте 5678 и 5432 без необходимости.</span></div></div></section>
<section id="decision" class="section"><p class="eyebrow">CLOUD ИЛИ SELF-HOSTED</p><h2>Сравнивайте полную стоимость, а не только цену VPS</h2><div class="cards"><article><h3>Self-hosted VPS</h3><p>Больше контроля над инфраструктурой, данными и scaling. В TCO входят VPS, backups, monitoring и время администратора.</p></article><article><h3>n8n Cloud</h3><p>Меньше эксплуатационной работы, но экономика зависит от плана и executions. Сравнивайте лимиты, обслуживание и стоимость роста нагрузки.</p></article></div></section>
<section id="environment" class="split"><div><p class="eyebrow">СРЕДА VPS</p><h2>Что должен поддерживать сервер</h2><p>Linux VPS с Docker, persistent storage, стабильной сетью и контролем firewall.</p></div><div class="requirements"><div><b>Linux</b><span>Ubuntu/Debian и root/sudo упрощают Docker и обслуживание.</span></div><div><b>Persistent data</b><span>Данные n8n и PostgreSQL должны переживать пересоздание контейнеров.</span></div><div><b>Network</b><span>DNS, HTTPS и стабильный outbound-доступ к API.</span></div></div></section>
<section class="section dark"><p class="eyebrow">ПОДРОБНЫЕ РУКОВОДСТВА</p><h2>Отдельные production-интенты</h2><div class="cards"><article><h3><a href="rezervnoe-kopirovanie-n8n.html">Backup и восстановление</a></h3><p>DB, volumes, encryption key и реальный test restore.</p></article><article><h3><a href="bezopasnost-n8n-vps.html">Безопасность</a></h3><p>HTTPS, firewall, SSH, MFA и защита execution data.</p></article><article><h3><a href="rezhim-ocheredi-n8n.html">Queue mode</a></h3><p>Redis, workers, PostgreSQL и connection pool.</p></article><article><h3><a href="n8n-cloud-vs-self-hosted.html">Cloud vs self-hosted</a></h3><p>TCO, executions, контроль данных и эксплуатационная ответственность.</p></article></div></section>
<section id="faq" class="section"><p class="eyebrow">FAQ</p><h2>Короткие ответы</h2><div class="faq"><details open><summary>Сколько RAM нужно n8n?</summary><p>2 GB может хватать для лёгких задач; 4 GB — практичная стартовая точка небольшого production; тяжёлые и AI-workflows часто требуют 8 GB и больше.</p></details><details><summary>Нужен ли Redis?</summary><p>Нет в обычном режиме. Redis нужен для queue mode с workers.</p></details><details><summary>Можно ли запускать n8n в Docker?</summary><p>Да. Для production обычно используют Docker/Compose, PostgreSQL, reverse proxy, HTTPS и persistent volumes.</p></details></div></section>
'''
new=s[:s.find("<main>")]+hero+content+tail
f.write_text(new,encoding="utf-8")
print("RU_HOME_EXPANDED",len(new))
