from pathlib import Path
r=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site")
maps={
"es":{"WORKLOAD SIZING":"DIMENSIONAMIENTO POR CARGA","n8n VPS sizing by workload":"Dimensionamiento del VPS para n8n según la carga","OPTIMIZE FIRST":"OPTIMIZA ANTES DE ESCALAR","Reduce avoidable resource usage before scaling":"Reduce el consumo innecesario antes de ampliar el VPS","REQUIREMENTS":"REQUISITOS","CPU, RAM and storage":"CPU, RAM y almacenamiento","PRODUCTION ARCHITECTURE":"ARQUITECTURA DE PRODUCCIÓN","Build for reliability":"Diseña para la fiabilidad","PRODUCTION CHECKLIST":"LISTA DE PRODUCCIÓN","Beyond CPU and RAM":"Más allá de CPU y RAM","OPERATIONS":"OPERACIÓN","Self-hosting means operational ownership":"El autoalojamiento implica responsabilidad operativa","CLOUD VS SELF-HOSTED":"CLOUD VS AUTOALOJADO","Compare total cost and responsibility":"Compara coste total y responsabilidad","VPS ENVIRONMENT":"ENTORNO VPS","What the server must support":"Qué debe soportar el servidor","n8n VPS FAQ":"Preguntas sobre VPS para n8n"},
"pt-br":{"WORKLOAD SIZING":"DIMENSIONAMENTO POR CARGA","n8n VPS sizing by workload":"Dimensionamento do VPS para n8n por carga","OPTIMIZE FIRST":"OTIMIZE ANTES DE ESCALAR","Reduce avoidable resource usage before scaling":"Reduza o consumo desnecessário antes de ampliar o VPS","REQUIREMENTS":"REQUISITOS","CPU, RAM and storage":"CPU, RAM e armazenamento","PRODUCTION ARCHITECTURE":"ARQUITETURA DE PRODUÇÃO","Build for reliability":"Projete para confiabilidade","PRODUCTION CHECKLIST":"CHECKLIST DE PRODUÇÃO","Beyond CPU and RAM":"Além de CPU e RAM","OPERATIONS":"OPERAÇÃO","Self-hosting means operational ownership":"Self-hosted exige responsabilidade operacional","CLOUD VS SELF-HOSTED":"CLOUD VS SELF-HOSTED","Compare total cost and responsibility":"Compare custo total e responsabilidade","VPS ENVIRONMENT":"AMBIENTE VPS","What the server must support":"O que o servidor deve suportar","n8n VPS FAQ":"Perguntas sobre VPS para n8n"},
"de":{"WORKLOAD SIZING":"DIMENSIONIERUNG NACH LAST","n8n VPS sizing by workload":"n8n-VPS nach Workload dimensionieren","OPTIMIZE FIRST":"ZUERST OPTIMIEREN","Reduce avoidable resource usage before scaling":"Unnötigen Ressourcenverbrauch vor dem Skalieren reduzieren","REQUIREMENTS":"ANFORDERUNGEN","CPU, RAM and storage":"CPU, RAM und Speicher","PRODUCTION ARCHITECTURE":"PRODUKTIONSARCHITEKTUR","Build for reliability":"Auf Zuverlässigkeit auslegen","PRODUCTION CHECKLIST":"PRODUKTIONS-CHECKLISTE","Beyond CPU and RAM":"Mehr als CPU und RAM","OPERATIONS":"BETRIEB","Self-hosting means operational ownership":"Self-Hosting bedeutet Betriebsverantwortung","CLOUD VS SELF-HOSTED":"CLOUD VS SELF-HOSTED","Compare total cost and responsibility":"Gesamtkosten und Verantwortung vergleichen","VPS ENVIRONMENT":"VPS-UMGEBUNG","What the server must support":"Was der Server unterstützen muss","n8n VPS FAQ":"Fragen zum n8n-VPS"},
"hi":{"WORKLOAD SIZING":"वर्कलोड के अनुसार साइज़िंग","n8n VPS sizing by workload":"वर्कलोड के अनुसार n8n VPS साइज़िंग","OPTIMIZE FIRST":"पहले ऑप्टिमाइज़ करें","Reduce avoidable resource usage before scaling":"स्केल करने से पहले अनावश्यक संसाधन उपयोग घटाएँ","REQUIREMENTS":"आवश्यकताएँ","CPU, RAM and storage":"CPU, RAM और स्टोरेज","PRODUCTION ARCHITECTURE":"प्रोडक्शन आर्किटेक्चर","Build for reliability":"विश्वसनीयता के लिए बनाएं","PRODUCTION CHECKLIST":"प्रोडक्शन चेकलिस्ट","Beyond CPU and RAM":"CPU और RAM से आगे","OPERATIONS":"ऑपरेशन","Self-hosting means operational ownership":"Self-hosting में संचालन की जिम्मेदारी आपकी है","CLOUD VS SELF-HOSTED":"CLOUD बनाम SELF-HOSTED","Compare total cost and responsibility":"कुल लागत और जिम्मेदारी की तुलना करें","VPS ENVIRONMENT":"VPS वातावरण","What the server must support":"सर्वर में क्या होना चाहिए","n8n VPS FAQ":"n8n VPS सवाल"},
"bn":{"WORKLOAD SIZING":"ওয়ার্কলোড অনুযায়ী সাইজিং","n8n VPS sizing by workload":"ওয়ার্কলোড অনুযায়ী n8n VPS সাইজিং","OPTIMIZE FIRST":"আগে অপ্টিমাইজ করুন","Reduce avoidable resource usage before scaling":"স্কেল করার আগে অপ্রয়োজনীয় resource usage কমান","REQUIREMENTS":"প্রয়োজনীয়তা","CPU, RAM and storage":"CPU, RAM ও storage","PRODUCTION ARCHITECTURE":"প্রোডাকশন আর্কিটেকচার","Build for reliability":"নির্ভরযোগ্যতার জন্য তৈরি করুন","PRODUCTION CHECKLIST":"প্রোডাকশন চেকলিস্ট","Beyond CPU and RAM":"CPU ও RAM-এর বাইরে","OPERATIONS":"অপারেশন","Self-hosting means operational ownership":"Self-hosting মানে operational responsibility","CLOUD VS SELF-HOSTED":"CLOUD বনাম SELF-HOSTED","Compare total cost and responsibility":"মোট খরচ ও দায়িত্ব তুলনা করুন","VPS ENVIRONMENT":"VPS পরিবেশ","What the server must support":"সার্ভারে কী support থাকতে হবে","n8n VPS FAQ":"n8n VPS প্রশ্ন"},
"ja":{"WORKLOAD SIZING":"ワークロード別サイジング","n8n VPS sizing by workload":"ワークロード別のn8n VPSサイジング","OPTIMIZE FIRST":"まず最適化","Reduce avoidable resource usage before scaling":"スケール前に不要なリソース消費を減らす","REQUIREMENTS":"要件","CPU, RAM and storage":"CPU・RAM・ストレージ","PRODUCTION ARCHITECTURE":"本番アーキテクチャ","Build for reliability":"信頼性を前提に構築","PRODUCTION CHECKLIST":"本番チェックリスト","Beyond CPU and RAM":"CPUとRAM以外の要件","OPERATIONS":"運用","Self-hosting means operational ownership":"セルフホストでは運用責任を持つ","CLOUD VS SELF-HOSTED":"CLOUD VS セルフホスト","Compare total cost and responsibility":"総コストと責任を比較","VPS ENVIRONMENT":"VPS環境","What the server must support":"サーバーに必要な機能","n8n VPS FAQ":"n8n VPS よくある質問"},
"pa":{"WORKLOAD SIZING":"ਵਰਕਲੋਡ ਅਨੁਸਾਰ ਸਾਈਜ਼ਿੰਗ","n8n VPS sizing by workload":"ਵਰਕਲੋਡ ਅਨੁਸਾਰ n8n VPS ਸਾਈਜ਼ਿੰਗ","OPTIMIZE FIRST":"ਪਹਿਲਾਂ OPTIMIZE ਕਰੋ","Reduce avoidable resource usage before scaling":"ਸਕੇਲ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਫ਼ਜ਼ੂਲ resource usage ਘਟਾਓ","REQUIREMENTS":"ਲੋੜਾਂ","CPU, RAM and storage":"CPU, RAM ਅਤੇ storage","PRODUCTION ARCHITECTURE":"PRODUCTION ਆਰਕੀਟੈਕਚਰ","Build for reliability":"ਭਰੋਸੇਯੋਗਤਾ ਲਈ ਬਣਾਓ","PRODUCTION CHECKLIST":"PRODUCTION CHECKLIST","Beyond CPU and RAM":"CPU ਅਤੇ RAM ਤੋਂ ਅੱਗੇ","OPERATIONS":"OPERATIONS","Self-hosting means operational ownership":"Self-hosting ਵਿੱਚ operations ਦੀ responsibility ਤੁਹਾਡੀ ਹੈ","CLOUD VS SELF-HOSTED":"CLOUD VS SELF-HOSTED","Compare total cost and responsibility":"ਕੁੱਲ cost ਅਤੇ responsibility compare ਕਰੋ","VPS ENVIRONMENT":"VPS ENVIRONMENT","What the server must support":"Server ਕੀ support ਕਰੇ","n8n VPS FAQ":"n8n VPS ਸਵਾਲ"}}
for lang,mp in maps.items():
 f=r/lang/"index.html";s=f.read_text(encoding="utf-8")
 for a,b in mp.items():s=s.replace(a,b)
 f.write_text(s,encoding="utf-8")
print("LOCALIZED",len(maps))
