from pathlib import Path
r=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site")
phrases=[
"Size the server from concurrency, payload size, AI/Code nodes, binary data and supporting services—not workflow count alone.",
"Minimum specs are not a production guarantee. Leave headroom for Docker, PostgreSQL and reverse proxy.",
"Queue mode adds Redis and workers. Preserve N8N_ENCRYPTION_KEY and keep persistent data off ephemeral containers.",
"Persistent volumes and private database access.","Domain, reverse proxy and correct WEBHOOK_URL.","Back up DB, data and encryption key.","Control execution history and binary-data growth.",
"OS, network, Docker, updates, monitoring, security and recovery remain your responsibility unless a managed plan explicitly includes them.",
"Stable public HTTPS address.","Pin versions and back up before upgrades.","Watch OOM, swap, CPU/RAM, disk and latency.","Firewall, SSH keys, MFA and private DB ports.",
"Infrastructure and data control with maintenance responsibility.","Lower operational overhead with plan/execution economics.",
"Linux, Docker, persistent storage, DNS, HTTPS and reliable outbound connectivity.","Ubuntu/Debian with root or sudo.","Survive container recreation and upgrades.","Firewall control and stable API/webhook access.",
"2 GB can suit light workloads; 4 GB is a practical small-production baseline; heavy/AI workloads often need 8 GB+.","Not in regular mode. Redis is used for queue mode with workers.","Yes. Docker/Compose with PostgreSQL and a reverse proxy is a practical production model."
]
# concise full-localization replacements in each language
T={
"es":["Dimensiona por concurrencia, payload, IA, datos binarios y servicios auxiliares, no solo por número de workflows.","Las especificaciones mínimas no garantizan producción. Deja margen para Docker, PostgreSQL y reverse proxy.","Queue mode añade Redis y workers. Conserva N8N_ENCRYPTION_KEY y datos persistentes.","Volúmenes persistentes y base de datos privada.","Dominio, reverse proxy y WEBHOOK_URL correcto.","Copia DB, datos y clave de cifrado.","Controla historial y crecimiento de datos binarios.","En self-hosted, sistema, red, Docker, actualizaciones, monitorización, seguridad y recuperación son tu responsabilidad salvo servicio gestionado.","Dirección HTTPS pública estable.","Fija versiones y haz backup antes de actualizar.","Vigila OOM, swap, CPU/RAM, disco y latencia.","Firewall, claves SSH, MFA y puertos de DB privados.","Control de infraestructura y datos con responsabilidad de mantenimiento.","Menos carga operativa con economía por plan/ejecuciones.","Linux, Docker, almacenamiento persistente, DNS, HTTPS y salida estable.","Ubuntu/Debian con root o sudo.","Los datos sobreviven a recreación y upgrades.","Firewall y acceso estable a API/webhooks.","2 GB para cargas ligeras; 4 GB como base práctica; 8 GB+ para cargas pesadas/IA.","No en modo normal. Redis se usa con queue mode y workers.","Sí. Docker/Compose con PostgreSQL y reverse proxy es un modelo práctico."],
"pt-br":["Dimensione por concorrência, payload, IA, dados binários e serviços auxiliares, não só pelo número de workflows.","Especificações mínimas não garantem produção. Mantenha folga para Docker, PostgreSQL e reverse proxy.","Queue mode adiciona Redis e workers. Preserve N8N_ENCRYPTION_KEY e dados persistentes.","Volumes persistentes e banco privado.","Domínio, reverse proxy e WEBHOOK_URL correto.","Faça backup do DB, dados e chave de criptografia.","Controle histórico e crescimento de dados binários.","No self-hosted, sistema, rede, Docker, updates, monitoramento, segurança e recuperação são sua responsabilidade salvo plano gerenciado.","Endereço HTTPS público estável.","Fixe versões e faça backup antes de atualizar.","Monitore OOM, swap, CPU/RAM, disco e latência.","Firewall, chaves SSH, MFA e portas do DB privadas.","Controle de infraestrutura e dados com responsabilidade de manutenção.","Menor carga operacional com economia por plano/executions.","Linux, Docker, armazenamento persistente, DNS, HTTPS e saída confiável.","Ubuntu/Debian com root ou sudo.","Dados sobrevivem à recriação e upgrades.","Firewall e acesso estável a APIs/webhooks.","2 GB para cargas leves; 4 GB como base prática; 8 GB+ para cargas pesadas/IA.","Não no modo normal. Redis é usado no queue mode com workers.","Sim. Docker/Compose com PostgreSQL e reverse proxy é um modelo prático."],
"de":["Nach Concurrency, Payload, AI, Binärdaten und Zusatzdiensten dimensionieren, nicht nur nach Workflow-Anzahl.","Minimale Specs sind keine Produktionsgarantie. Reserve für Docker, PostgreSQL und Reverse Proxy einplanen.","Queue Mode ergänzt Redis und Worker. N8N_ENCRYPTION_KEY und persistente Daten sichern.","Persistente Volumes und private Datenbank.","Domain, Reverse Proxy und korrekte WEBHOOK_URL.","DB, Daten und Encryption Key sichern.","Execution-Historie und Binärdatenwachstum begrenzen.","Bei Self-Hosting liegen OS, Netzwerk, Docker, Updates, Monitoring, Sicherheit und Recovery bei dir, sofern kein Managed-Plan dies übernimmt.","Stabile öffentliche HTTPS-Adresse.","Versionen pinnen und vor Updates sichern.","OOM, Swap, CPU/RAM, Disk und Latenz überwachen.","Firewall, SSH-Keys, MFA und private DB-Ports.","Infrastruktur- und Datenkontrolle mit Wartungsverantwortung.","Weniger Betriebsaufwand mit Plan-/Execution-Kosten.","Linux, Docker, persistenter Speicher, DNS, HTTPS und zuverlässiger Outbound-Zugriff.","Ubuntu/Debian mit root oder sudo.","Daten überstehen Container-Neuerstellung und Upgrades.","Firewall und stabiler API/Webhook-Zugriff.","2 GB für leichte Last; 4 GB als praktische Basis; 8 GB+ für schwere/AI-Last.","Nicht im normalen Modus. Redis wird für Queue Mode mit Workern genutzt.","Ja. Docker/Compose mit PostgreSQL und Reverse Proxy ist ein praktikables Modell."],
"hi":["साइज़िंग concurrency, payload, AI, binary data और सहायक services से करें, केवल workflow count से नहीं।","Minimum specs production की गारंटी नहीं हैं। Docker, PostgreSQL और reverse proxy के लिए headroom रखें।","Queue mode में Redis और workers जुड़ते हैं। N8N_ENCRYPTION_KEY और persistent data सुरक्षित रखें।","Persistent volumes और private database access।","Domain, reverse proxy और सही WEBHOOK_URL।","DB, data और encryption key का backup रखें।","Execution history और binary-data growth नियंत्रित करें।","Self-hosted में OS, network, Docker, updates, monitoring, security और recovery आपकी जिम्मेदारी है, जब तक managed plan इन्हें शामिल न करे।","स्थिर public HTTPS address।","Versions pin करें और upgrade से पहले backup लें।","OOM, swap, CPU/RAM, disk और latency monitor करें।","Firewall, SSH keys, MFA और private DB ports।","Maintenance responsibility के साथ infrastructure और data control।","Plan/execution economics के साथ कम operational overhead।","Linux, Docker, persistent storage, DNS, HTTPS और reliable outbound connectivity।","Ubuntu/Debian with root या sudo।","Data container recreation और upgrades के बाद भी सुरक्षित रहे।","Firewall control और stable API/webhook access।","Light workload के लिए 2 GB; practical production baseline 4 GB; heavy/AI के लिए 8 GB+।","Regular mode में नहीं। Redis queue mode और workers के लिए है।","हाँ। PostgreSQL और reverse proxy के साथ Docker/Compose practical production model है।"],
"bn":["Concurrency, payload, AI, binary data ও supporting services দেখে sizing করুন, শুধু workflow count নয়।","Minimum specs production guarantee নয়। Docker, PostgreSQL ও reverse proxy-এর জন্য headroom রাখুন।","Queue mode-এ Redis ও workers যোগ হয়। N8N_ENCRYPTION_KEY এবং persistent data সুরক্ষিত রাখুন।","Persistent volumes এবং private database access।","Domain, reverse proxy এবং সঠিক WEBHOOK_URL।","DB, data এবং encryption key backup করুন।","Execution history এবং binary-data growth নিয়ন্ত্রণ করুন।","Self-hosted-এ OS, network, Docker, updates, monitoring, security ও recovery আপনার দায়িত্ব, managed plan না থাকলে।","স্থিতিশীল public HTTPS address।","Version pin করুন এবং upgrade-এর আগে backup নিন।","OOM, swap, CPU/RAM, disk ও latency monitor করুন।","Firewall, SSH keys, MFA এবং private DB ports।","Maintenance responsibility সহ infrastructure ও data control।","Plan/execution economics সহ কম operational overhead।","Linux, Docker, persistent storage, DNS, HTTPS এবং reliable outbound connectivity।","Ubuntu/Debian with root বা sudo।","Container recreation ও upgrades-এর পরেও data থাকে।","Firewall control এবং stable API/webhook access।","Light workload-এ 2 GB; practical baseline 4 GB; heavy/AI-তে 8 GB+।","Regular mode-এ নয়। Redis queue mode ও workers-এর জন্য।","হ্যাঁ। PostgreSQL ও reverse proxy সহ Docker/Compose practical production model।"],
"ja":["Concurrency、payload、AI、binary data、周辺サービスからサイジングし、workflow数だけで判断しません。","最小スペックは本番保証ではありません。Docker、PostgreSQL、reverse proxyの余裕を確保します。","Queue modeではRedisとworkersを追加します。N8N_ENCRYPTION_KEYとpersistent dataを保護します。","Persistent volumeと非公開DBアクセス。","Domain、reverse proxy、正しいWEBHOOK_URL。","DB、data、encryption keyをバックアップ。","Execution historyとbinary dataの増加を管理。","Self-hostedではOS、network、Docker、updates、monitoring、security、recoveryは運用者責任です。Managed planに含まれる範囲は確認します。","安定した公開HTTPSアドレス。","Versionを固定し、upgrade前にbackup。","OOM、swap、CPU/RAM、disk、latencyを監視。","Firewall、SSH key、MFA、非公開DB ports。","保守責任と引き換えにinfrastructureとdataを制御。","Plan/execution料金と引き換えに運用負荷を削減。","Linux、Docker、persistent storage、DNS、HTTPS、安定したoutbound通信。","Ubuntu/Debianでrootまたはsudo。","Container再作成やupgrade後もdataを保持。","Firewall controlと安定したAPI/webhook access。","軽量は2 GB、本番の実用基準は4 GB、heavy/AIは8 GB+。","通常モードでは不要。Redisはqueue modeとworkersで使用します。","はい。PostgreSQLとreverse proxyを組み合わせたDocker/Composeは実用的です。"],
"pa":["Sizing concurrency, payload, AI, binary data ਅਤੇ supporting services ਦੇ ਅਧਾਰ ਤੇ ਕਰੋ, ਸਿਰਫ workflow count ਤੇ ਨਹੀਂ।","Minimum specs production guarantee ਨਹੀਂ ਹਨ। Docker, PostgreSQL ਅਤੇ reverse proxy ਲਈ headroom ਰੱਖੋ।","Queue mode ਵਿੱਚ Redis ਅਤੇ workers ਸ਼ਾਮਲ ਹੁੰਦੇ ਹਨ। N8N_ENCRYPTION_KEY ਅਤੇ persistent data ਸੁਰੱਖਿਅਤ ਰੱਖੋ।","Persistent volumes ਅਤੇ private database access।","Domain, reverse proxy ਅਤੇ ਸਹੀ WEBHOOK_URL।","DB, data ਅਤੇ encryption key ਦਾ backup ਰੱਖੋ।","Execution history ਅਤੇ binary-data growth control ਕਰੋ।","Self-hosted ਵਿੱਚ OS, network, Docker, updates, monitoring, security ਅਤੇ recovery ਤੁਹਾਡੀ responsibility ਹੈ, ਜਦ ਤੱਕ managed plan ਇਹ ਨਾ ਲਵੇ।","Stable public HTTPS address।","Versions pin ਕਰੋ ਅਤੇ upgrade ਤੋਂ ਪਹਿਲਾਂ backup ਲਵੋ।","OOM, swap, CPU/RAM, disk ਅਤੇ latency monitor ਕਰੋ।","Firewall, SSH keys, MFA ਅਤੇ private DB ports।","Maintenance responsibility ਨਾਲ infrastructure ਅਤੇ data control।","Plan/execution economics ਨਾਲ ਘੱਟ operational overhead।","Linux, Docker, persistent storage, DNS, HTTPS ਅਤੇ reliable outbound connectivity।","Ubuntu/Debian with root ਜਾਂ sudo।","Data container recreation ਅਤੇ upgrades ਤੋਂ ਬਾਅਦ ਵੀ ਰਹੇ।","Firewall control ਅਤੇ stable API/webhook access।","Light workload ਲਈ 2 GB; practical baseline 4 GB; heavy/AI ਲਈ 8 GB+।","Regular mode ਵਿੱਚ ਨਹੀਂ। Redis queue mode ਅਤੇ workers ਲਈ ਹੈ।","ਹਾਂ। PostgreSQL ਅਤੇ reverse proxy ਨਾਲ Docker/Compose practical production model ਹੈ।"]}
for lang,vals in T.items():
 f=r/lang/"index.html";s=f.read_text(encoding="utf-8")
 for a,b in zip(phrases,vals):s=s.replace(a,b)
 f.write_text(s,encoding="utf-8")
print("BODY_LOCALIZED")
