from pathlib import Path
r=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site")
common=["SELF-HOSTED AUTOMATION INFRASTRUCTURE","Testing, learning and low concurrency.","AI, files, large payloads and parallel executions.","Limit execution retention and old data.","Stagger heavy schedules where possible.","Reduce unnecessary large JSON and binary data.","Scale from observed RAM, CPU, disk and latency.","1–2 vCPU light; more for concurrency.","SSD/NVMe for DB, history, logs and Docker data."]
T={
"es":["INFRAESTRUCTURA DE AUTOMATIZACIÓN AUTOALOJADA","Pruebas, aprendizaje y baja concurrencia.","IA, archivos, payloads grandes y ejecuciones paralelas.","Limita la retención de ejecuciones y datos antiguos.","Escalona tareas pesadas cuando sea posible.","Reduce JSON grande y datos binarios innecesarios.","Escala según RAM, CPU, disco y latencia medidos.","1–2 vCPU para carga ligera; más para concurrencia.","SSD/NVMe para DB, historial, logs y datos Docker."],
"pt-br":["INFRAESTRUTURA DE AUTOMAÇÃO SELF-HOSTED","Testes, aprendizado e baixa concorrência.","IA, arquivos, payloads grandes e execuções paralelas.","Limite retenção de execuções e dados antigos.","Distribua tarefas pesadas quando possível.","Reduza JSON grande e dados binários desnecessários.","Escale conforme RAM, CPU, disco e latência medidos.","1–2 vCPU para carga leve; mais para concorrência.","SSD/NVMe para DB, histórico, logs e dados Docker."],
"de":["SELF-HOSTED-AUTOMATISIERUNGSINFRASTRUKTUR","Tests, Lernen und geringe Parallelität.","AI, Dateien, große Payloads und parallele Ausführungen.","Execution-Aufbewahrung und alte Daten begrenzen.","Schwere Zeitpläne möglichst verteilen.","Unnötig große JSON- und Binärdaten reduzieren.","Nach gemessener RAM-, CPU-, Disk- und Latenzlast skalieren.","1–2 vCPU für leichte Last; mehr bei Parallelität.","SSD/NVMe für DB, Historie, Logs und Docker-Daten."],
"hi":["SELF-HOSTED ऑटोमेशन इंफ्रास्ट्रक्चर","Testing, सीखने और कम concurrency के लिए।","AI, files, बड़े payload और parallel executions।","Execution retention और पुराने data को सीमित रखें।","Heavy schedules को जहाँ संभव हो अलग समय पर चलाएँ।","अनावश्यक बड़े JSON और binary data घटाएँ।","Measured RAM, CPU, disk और latency के आधार पर scale करें।","Light load के लिए 1–2 vCPU; concurrency पर अधिक।","DB, history, logs और Docker data के लिए SSD/NVMe।"],
"bn":["SELF-HOSTED অটোমেশন ইনফ্রাস্ট্রাকচার","Testing, শেখা ও কম concurrency-এর জন্য।","AI, files, বড় payload ও parallel executions।","Execution retention ও পুরোনো data সীমিত করুন।","Heavy schedules সম্ভব হলে আলাদা সময়ে চালান।","অপ্রয়োজনীয় বড় JSON ও binary data কমান।","Measured RAM, CPU, disk ও latency দেখে scale করুন।","Light load-এ 1–2 vCPU; concurrency বাড়লে বেশি।","DB, history, logs ও Docker data-এর জন্য SSD/NVMe।"],
"ja":["セルフホスト自動化インフラ","テスト、学習、低い同時実行向け。","AI、ファイル、大きなpayload、並列実行向け。","Executionの保持期間と古いdataを制限します。","重いscheduleは可能なら時間を分散します。","不要な大容量JSONとbinary dataを減らします。","実測したRAM、CPU、disk、latencyからscaleします。","軽量負荷は1–2 vCPU、同時実行が増えれば追加。","DB、履歴、logs、Docker dataにはSSD/NVMe。"],
"pa":["SELF-HOSTED ਆਟੋਮੇਸ਼ਨ ਇਨਫਰਾਸਟਰਕਚਰ","Testing, learning ਅਤੇ ਘੱਟ concurrency ਲਈ।","AI, files, ਵੱਡੇ payload ਅਤੇ parallel executions।","Execution retention ਅਤੇ ਪੁਰਾਣਾ data ਸੀਮਿਤ ਕਰੋ।","Heavy schedules ਨੂੰ ਜਿੱਥੇ ਸੰਭਵ ਹੋਵੇ ਵੱਖਰੇ ਸਮੇਂ ਚਲਾਓ।","ਫ਼ਜ਼ੂਲ ਵੱਡੇ JSON ਅਤੇ binary data ਘਟਾਓ।","Measured RAM, CPU, disk ਅਤੇ latency ਦੇ ਅਧਾਰ ਤੇ scale ਕਰੋ।","Light load ਲਈ 1–2 vCPU; concurrency ਲਈ ਹੋਰ।","DB, history, logs ਅਤੇ Docker data ਲਈ SSD/NVMe।"]}
for lang,vals in T.items():
 f=r/lang/"index.html";s=f.read_text(encoding="utf-8")
 for a,b in zip(common,vals):s=s.replace(a,b)
 f.write_text(s,encoding="utf-8")
print("FIXED_CARD_PHRASES")
