from pathlib import Path
import re
r=Path(r"C:\Users\User\SEO_NICHE_RESEARCH\VPS for N8N\site")
langs=["es","pt-br","de","hi","bn","ja","pa"]
# language-neutral technical base; preserves each language's existing localized hero and SERP blocks
base=r'''
<section id="workloads" class="section"><p class="eyebrow">WORKLOAD SIZING</p><h2>n8n VPS sizing by workload</h2><p class="intro">Size the server from concurrency, payload size, AI/Code nodes, binary data and supporting services—not workflow count alone.</p><div class="cards"><article><h3>Light</h3><b>1–2 vCPU · 2 GB</b><p>Testing, learning and low concurrency.</p></article><article class="featured"><h3>Small production</h3><b>2 vCPU · 4 GB</b><p>Docker, PostgreSQL, HTTPS and headroom.</p></article><article><h3>Heavy / AI</h3><b>4+ vCPU · 8 GB+</b><p>AI, files, large payloads and parallel executions.</p></article><article><h3>Queue mode</h3><b>4+ vCPU · 8–16+ GB</b><p>Redis, PostgreSQL and workers.</p></article></div></section>
<section id="save" class="section dark"><p class="eyebrow">OPTIMIZE FIRST</p><h2>Reduce avoidable resource usage before scaling</h2><div class="cards"><article><h3>Pruning</h3><p>Limit execution retention and old data.</p></article><article><h3>Concurrency</h3><p>Stagger heavy schedules where possible.</p></article><article><h3>Payload</h3><p>Reduce unnecessary large JSON and binary data.</p></article><article><h3>Measure</h3><p>Scale from observed RAM, CPU, disk and latency.</p></article></div></section>
<section id="requirements" class="split"><div><p class="eyebrow">REQUIREMENTS</p><h2>CPU, RAM and storage</h2><p>Minimum specs are not a production guarantee. Leave headroom for Docker, PostgreSQL and reverse proxy.</p></div><div class="requirements"><div><b>CPU</b><span>1–2 vCPU light; more for concurrency.</span></div><div><b>RAM</b><span>2 GB testing · 4 GB production · 8 GB+ heavy.</span></div><div><b>Storage</b><span>SSD/NVMe for DB, history, logs and Docker data.</span></div></div></section>
<section id="architecture" class="section dark"><p class="eyebrow">PRODUCTION ARCHITECTURE</p><h2>Build for reliability</h2><div class="pipeline"><span>HTTPS</span><i>→</i><span>Reverse Proxy</span><i>→</i><span>n8n</span><i>→</i><span>PostgreSQL</span><i>→</i><span>Backups</span></div><p>Queue mode adds Redis and workers. Preserve N8N_ENCRYPTION_KEY and keep persistent data off ephemeral containers.</p></section>
<section id="production" class="section"><p class="eyebrow">PRODUCTION CHECKLIST</p><h2>Beyond CPU and RAM</h2><div class="cards"><article><h3>Docker + PostgreSQL</h3><p>Persistent volumes and private database access.</p></article><article><h3>HTTPS + Webhooks</h3><p>Domain, reverse proxy and correct WEBHOOK_URL.</p></article><article><h3>Encryption + Backup</h3><p>Back up DB, data and encryption key.</p></article><article><h3>Retention</h3><p>Control execution history and binary-data growth.</p></article></div></section>
<section id="operations" class="split"><div><p class="eyebrow">OPERATIONS</p><h2>Self-hosting means operational ownership</h2><p>OS, network, Docker, updates, monitoring, security and recovery remain your responsibility unless a managed plan explicitly includes them.</p></div><div class="requirements"><div><b>DNS</b><span>Stable public HTTPS address.</span></div><div><b>Updates</b><span>Pin versions and back up before upgrades.</span></div><div><b>Monitoring</b><span>Watch OOM, swap, CPU/RAM, disk and latency.</span></div><div><b>Security</b><span>Firewall, SSH keys, MFA and private DB ports.</span></div></div></section>
<section id="decision" class="section"><p class="eyebrow">CLOUD VS SELF-HOSTED</p><h2>Compare total cost and responsibility</h2><div class="cards"><article><h3>Self-hosted VPS</h3><p>Infrastructure and data control with maintenance responsibility.</p></article><article><h3>Managed Cloud</h3><p>Lower operational overhead with plan/execution economics.</p></article></div></section>
<section id="environment" class="split"><div><p class="eyebrow">VPS ENVIRONMENT</p><h2>What the server must support</h2><p>Linux, Docker, persistent storage, DNS, HTTPS and reliable outbound connectivity.</p></div><div class="requirements"><div><b>Linux</b><span>Ubuntu/Debian with root or sudo.</span></div><div><b>Persistent data</b><span>Survive container recreation and upgrades.</span></div><div><b>Network</b><span>Firewall control and stable API/webhook access.</span></div></div></section>
<section id="faq" class="section"><p class="eyebrow">FAQ</p><h2>n8n VPS FAQ</h2><div class="faq"><details open><summary>How much RAM?</summary><p>2 GB can suit light workloads; 4 GB is a practical small-production baseline; heavy/AI workloads often need 8 GB+.</p></details><details><summary>Is Redis required?</summary><p>Not in regular mode. Redis is used for queue mode with workers.</p></details><details><summary>Can n8n run in Docker?</summary><p>Yes. Docker/Compose with PostgreSQL and a reverse proxy is a practical production model.</p></details></div></section>
'''
for lang in langs:
 f=r/lang/"index.html";s=f.read_text(encoding="utf-8")
 if 'id="workloads"' not in s:
  pos=s.find("</main>")
  s=s[:pos]+base+s[pos:]
  f.write_text(s,encoding="utf-8")
print("RESTORED",len(langs))
